### ISSUE TITLE
Running true-cli with node-sass

### ISSUE THREAD

**Issue by eddie-ruva** [ericam/true#27]
I recently installed sass-true through npm. Everything has been working correctly but I'm just not able to use the cli without having to depend in ruby sass. I would love to help in adapt the cli functionality with node-sass and was wondering if a PR into this project would be helpful or if it makes more sense to create another npm package that only has the cli functionality. Any input in this would be greatly appreciated, thanks!

**Comment by carljm** [comment]
Hi,

So the documentation hasn't quite caught up here yet, but the idea is that rather than having a dedicated node-sass-based CLI runner for True, it instead integrates with an existing Node-based test runner (so far just Mocha, but support for others could be added). You can see an example of how that works with Mocha in True's own tests; the file `test/test_sass.js` runs the True tests in `test/scss/test.scss` using Mocha (by passing in Mocha's `describe` and `it` functions to `runSass`). This means Mocha understands the test results as individual tests and you can leverage all the existing reporting capabilities of Mocha, instead of needing to re-implement them in a True-specific test runner.

It would be possible to also have a very simple Node port of true-cli available; less flexible than integrating with existing test runners, but good enough for the simple cases. @ericam would have to speak to whether he'd be interested in merging such a thing if someone submitted a PR for it, but my guess is he would.

**Comment by ericam** [comment]
Yep, I'm happy for the PR if people would still find that useful apart from the Mocha integration.

**Comment by ericam** [comment]
`v2.0.1` includes full mocha support. Closing this for now, unless there is a strong desire for true-cli to also support node-sass.

**Comment by eddie-ruva** [comment]
@ericam @carljm  Sorry I did not respond on time for this. Running the tests with mocha works for what I was trying to do actually and it makes perfect sense. Thanks for the awesome work on this! :smiley:
